services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3501:3501"
    volumes:
      - ../src:/app/src
      - ../index.html:/app/index.html
      - ../vite.config.js:/app/vite.config.js
      - ../public:/app/public
